version: '3.6'
networks:
  spring-network:
    driver: bridge
    name: spring-network
  db-network:
    driver: bridge
    name: database-network
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springapp:v1
    container_name: spring-app
    restart: always
    ports:
      - '${PUBLIC_PORT}:${CONTAINER_PORT}'
    depends_on:
      - db
    networks:
      - spring-network
      - db-network
    env_file:
      - .env
  db:
    image: mysql:8.0-debian
    restart: unless-stopped
    container_name: mysql
    #    user: 1000:1000
    volumes:
      - .docker/data/db:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - db-network
    user: 999:999